version: '2.19.0'
services:
  mysql:
    image: mysql:8.0
    container_name: auto-mysql-db-${TAG}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - autobot_data:/var/lib/mysql
    networks:
      - autobot_net
  selenium-server:
    image: selenium/standalone-chrome
    container_name: auto-selenium-srv-${TAG}
    restart: always
    ports:
      - 4444:4444
      - 7900:7900
  web:
    image: nginx:latest
    container_name: auto-web-srv-${TAG}
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./build/images/nginx/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - autobot_net
  php-fpm:
    image: php:8.1-fpm
    container_name: auto-php-fpm-${TAG}
    volumes:
      - ./:/var/www/html
    networks:
      - autobot_net
volumes:
  autobot_data:
networks:
  autobot_net:
